### ISSUE TITLE
Add to Functional Dependencies

### ISSUE THREAD

**Issue by vyorkin** [vyorkin/purescript-dialogs#1]
http://www.cse.chalmers.se/~hallgren/Papers/hallgren.pdf

Example #1:

```PureScript
module Main where

-- | In Prolog:

-- even(zero).
-- even(succ(N)):-odd(N).
-- odd(succ(N)):-even(N).

data Proxy a = Proxy

data Zero
data Succ n

class Even n where
  even ∷ Proxy n

class Odd n where
  odd ∷ Proxy n

instance evenZero ∷ Even Zero where even = Proxy
instance evenNumber ∷ Odd n ⇒ Even (Succ n) where even = Proxy
instance oddNumber ∷ Even n ⇒ Odd (Succ n) where odd = Proxy

-- | Try in the PSCI
-- :t even :: (Proxy Succ (Succ Zero))
-- :t odd :: (Proxy Succ (Succ (Succ Zero)))

-- | This one succeeds
x ∷ Proxy (Succ (Succ Zero))
x = even

-- | This one fails
-- y ∷ Proxy (Succ (Succ (Succ Zero)))
-- y = even
```

Example #2:

```PureScript
module Main where

-- | In Prolog:

-- even(zero,true).
-- even(succ(N),B):-odd(N,B).
-- odd(zero,false).
-- odd(succ(N),B):-even(N,B).

data Proxy a b = Proxy

data Zero
data Succ n

data True
data False

class Even n b where
  even ∷ Proxy n b

class Odd n b where
  odd ∷ Proxy n b

instance evenZero ∷ Even Zero True where even = Proxy
instance evenNumber ∷ Odd n b ⇒ Even (Succ n) b where even = Proxy

instance oddZero ∷ Odd Zero False where odd = Proxy
instance oddNumber ∷ Even n b ⇒ Odd (Succ n) b where odd = Proxy

-- | Try in PSCI
-- :t odd :: (Proxy Zero False)
-- :t odd :: (Proxy Zero True)
-- :t even :: (Proxy (Succ (Succ Zero)) True)
-- :t even :: (Proxy (Succ (Succ Zero)) False)

-- | This one succeeds
x ∷ Proxy Zero False
x = odd

-- | This one fails
-- y ∷ Proxy Zero True
-- y = odd

-- without having functional dependencies
-- its possible to declare at the same time both:

-- instance evenZeroT ∷ Even Zero True where even = Proxy
-- instance evenZeroF ∷ Even Zero False where even = Proxy

-- this is possible because in `class Even n b`
-- could be any relation between `n` and `b`,
-- not only "functonal" relation (like `n → b`)
```

**Comment by paluh** [comment]
@vyorkin Maybe even add link to live demo(s): http://try.purescript.org/?gist=cef92915b6348b18149a5dc347b36e26

**Comment by vyorkin** [comment]
I'm working through the paper, going to add more complex examples with operations & mixing dynamic and static computations soon

**Comment by paluh** [comment]
Side note:
I'm not sure this is the best approach but if you are trying to use gist+try.purescript.org I've found that a way to refresh gist in try.purescript is to open it up in incognito (and possibly refresh a couple of times ;-)) with only `?gist=` parameter (I'm creating bookmark for myself with such an url to speedup workflow).

**Comment by vyorkin** [comment]
ex1: http://try.purescript.org/?gist=b93cd253c65bea68e703bf85d214ab49
ex2: http://try.purescript.org/?gist=a36a1519a9ca45cb8394282e87b7918c
ex3: http://try.purescript.org/?gist=4dd60313ac753c4c9623e1ae5b712b35
ex4: http://try.purescript.org/?gist=e9b85b4ba021704321d8fa8fbd351587

**Comment by vyorkin** [comment]
I've tried to play around with the insertion sort example mentioned in the paper, but I'm not sure it works.
I've created a separate issue to come back and play with it later: #2 
But I think I've got the idea
http://try.purescript.org/?gist=d5763a38491b36b2ad8aa9fabbfce9cc
I also left some comments there

![img_8592](https://user-images.githubusercontent.com/988849/39088522-4dd13b32-45bc-11e8-8f86-a22cb65a8fb1.JPG)
